### ISSUE TITLE
Doesn't work in custom dimensions

### ISSUE THREAD

**Issue by pooky125** [tpwalke2/BlueMapSignMarkers#44]
This is a pretty niche problem, but I run a couple custom dimensions on my server, and would really love to find a way to make it work across additional dimensions. 

This is the error message that pops up on the console.

[05:12:48] [pool-12-thread-4/INFO]: Processing marker action: AddMarkerAction{markerIdentifier=MarkerIdentifier[x=24, y=117, z=27, parentSet=MarkerSetIdentifier[map=UNKNOWN, markerType=POI]], label='Hankmart', detail='Hankmart'}
[05:12:48] [pool-12-thread-4/WARN]: Unknown map: UNKNOWN
[05:12:48] [pool-12-thread-4/WARN]: Marker set not found.

**Comment by tpwalke2** [comment]
This is a good one. I've not run custom dimensions except in modded and that was years ago.

Do you happen to have some info about how to make a custom dimension? Before I attempt an update for them, I'd like to make sure I can test the scenario.

**Comment by pooky125** [comment]
Yes, absolutely. 

This is probably my favorite website for setting up custom dimensions. In the datapack, you'll need both a dimension, and a dimension type file, with the same name.

https://misode.github.io/dimension/
https://misode.github.io/dimension-type/

However, *speaking from personal experience*, they can be a bit fiddly to get working, so I've also included a pack that has my custom dimension files in it, so you can see what multiple choices look like, and how theyre formatted. This is a functional datapack  that should work in 1.20+

[Custom Dimensions.zip](https://github.com/tpwalke2/BlueMapSignMarkers/files/14002562/Custom.Dimensions.zip)

To actually GET to the custom dimensions, the minecraft command is /execute in <dimension name> run teleport <player name> <coordinates>

You WILL need to restart the world before custom dimensions will generate after adding in the pack. 

If you have any questions, please reach back out, I'd love to offer as much assistance as I can, custom dimensions are a pretty cool feature I've been using since they were released in 1.16. It's a shame they aren't used more often.

**Comment by tpwalke2** [comment]
Thank you for this data pack. It has helped.

I have a potential update in a side-branch that I'm going to test against a backup of my family's map.

I found that the sign cache file will need to change slightly, due to a change in how each dimension id is interpreted when loading. So I'm going to get a solution for #32 in first and then get this update in.

I expect both items to be included in the next release.

**Comment by pooky125** [comment]
Excellent, thank you! I'm glad to hear my data pack was useful for you.

I look forward to the update.

**Comment by tpwalke2** [comment]
@pooky125, I have released an alpha version here https://modrinth.com/mod/bluemap-sign-markers/version/1.20.1-0.0.4.7-alpha

I have tested it locally against a copy of my family's map and against a map with your data pack. I'm testing it against my family's server (with a backup in place).

If you would like to test the alpha, feel free. The mod will make a backup copy of the signs.json file before overwriting with the new signs format.

Once I am satisfied with what I see, I'll make a regular release, in case you would feel more comfortable waiting for that.

**Comment by tpwalke2** [comment]
Hi @pooky125, have you updated to 1.21? If so, do you have an updated dimensions data pack? Mojang made some breaking changes to the datapack format since 1.20.1. I'm testing updates to this mod for 1.21 and want to make sure the custom dimensions still work.

**Comment by pooky125** [comment]
Hello!

So, I haven't updated to 1.21 yet, because I'm still in progress updating my datapack. However, the dimension aspect of that is completed. I'll send you the files when I'm back at my pc in a few hours.

**Comment by pooky125** [comment]
[CustomDimensions.zip](https://github.com/user-attachments/files/16199783/CustomDimensions.zip)

@tpwalke2 Here you go! Sorry I forgot about it yesterday, I've been having internet issues!

**Comment by tpwalke2** [comment]
Thank you so much @pooky125!

Those have helped with the testing of the 1.21 updates.
