### ISSUE TITLE
Allow regular expressions in prefixes

### ISSUE THREAD

**Issue by elboletaire** [tpwalke2/BlueMapSignMarkers#66]
I come from overviewer where we could define these via regular expressions, and  that really reduced my config a lot, since now I have to add multiple definitions to check stuff like uppercase (i.e. I have three prefixes for "portal": `Portal`, `portal` & `PORTAL`)

A way to define to ignore case would also be welcome, but having case sensitive regular expressions would already simplify it a lot.

**Comment by tpwalke2** [comment]
I came from overviewer also and it was a lot simpler to have a script that watched for these signs.

This is a good idea. Thank you for sharing!

**Comment by tpwalke2** [comment]
@elboletaire, I have merged the PR (https://github.com/tpwalke2/BlueMapSignMarkers/pull/72) for this update to `main`. Take a look at https://github.com/tpwalke2/BlueMapSignMarkers?tab=readme-ov-file#example for an example of how to configure the regex marker group.

There are a few other items I am targeting for the same version (1.21.1-0.4.0), however. You can track the progress of those issues here: https://github.com/tpwalke2/BlueMapSignMarkers/issues?q=is%3Aissue+is%3Aopen+label%3A1.21.1-0.4.0

**Comment by tpwalke2** [comment]
@elboletaire, I have published a release to modrinth that includes this update: https://modrinth.com/mod/bluemap-sign-markers/version/1.21-0.4.0.30
