### ISSUE TITLE
TP to a sign marker

### ISSUE THREAD

**Issue by rohoal1012** [tpwalke2/BlueMapSignMarkers#76]
Add a command o a option so the players inside the server can tp to the signs plisssss

**Comment by tpwalke2** [comment]
I see that you opened a similar issue in the BlueMap repository (https://github.com/MiraculixxT/bluemap-marker/issues/41). I think it makes more sense to have teleporting to markers at that level or as a separate mod that looks at all of the available markers. This is not a direction I want to take this mod, however.
