### ISSUE TITLE
Custom icons results in weird behavior

### ISSUE THREAD

**Issue by damondriscoll** [tpwalke2/BlueMapSignMarkers#80]
The icon won’t anchor correctly to its relative map location, I assume it’s not applying the correct CSS? Even manually assigning the icon as “assets/poi.svg” breaks it

**Comment by tpwalke2** [comment]
Can you share a screenshot showing the behavior?

**Comment by damondriscoll** [comment]
Yes, I’ll update by tomorrow night

**Comment by damondriscoll** [comment]
I found out the issue - apparently the default anchor settings (0, 0) are messed up, as for SVGs at least, it completely breaks them! I used anchor settings found on the BlueMap website (25, 45), and they work as intended.

(25, 45), correct
![image](https://github.com/user-attachments/assets/b8d4f9c0-dff6-4718-9667-d6c4582bcabe)

(0, 0), wrong, becomes more obvious when scaled out
![image](https://github.com/user-attachments/assets/2de133bb-4307-4228-a5b7-5706977cd41b)

I'll create the PR tomorrow shouldn't be that difficult (i think)

**Comment by tpwalke2** [comment]
I don't think a PR is necessary as this is working as designed. The `offsetX` and `offsetY` are read from the config and allow users to modify the location for each marker type (https://github.com/tpwalke2/BlueMapSignMarkers?tab=readme-ov-file#marker-groups).
